# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

stages:
 - stage: Build
   jobs:
   - job: Build
     pool:
      vmImage: 'vs2017-win2016'


     steps:
     - task: Maven@3
       inputs:
         mavenPomFile: 'pom.xml'
         mavenOptions: '-Xmx3072m'
         javaHomeOption: 'JDKVersion'
         jdkVersionOption: '1.8'
         jdkArchitectureOption: 'x64'
         publishJUnitResults: true
         testResultsFiles: '**/surefire-reports/TEST-*.xml'
         goals: 'package'

     - task: PublishBuildArtifacts@1
       inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'drop'
         publishLocation: 'Container'

 - stage: deploy
   jobs:
   - deployment: DeployWeb
     displayName: deploy Web App
    
    # creates an environment if it doesn't exis
     environment: 'smarthotel-dev'
     strategy: 
        runOnce:
          deploy:
            steps:
            - task: DownloadBuildArtifacts@0
              inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: 'drop'
               downloadPath: '$(Build.ArtifactStagingDirectory)'

            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                script: 'Get-ChildItem -Path $(Build.ArtifactStagingDirectory) -Recurse -Force'
              condition: always()
            